version: '3.8'

services:
  db:
    image: postgres:15
    container_name: blog_db
    environment:
      POSTGRES_DB: blog_db
      POSTGRES_USER: blog_user
      POSTGRES_PASSWORD: blog_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blog_user -d blog_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    build: .
    container_name: blog_api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://blog_user:blog_password@db:5432/blog_db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
